### ISSUE TITLE
Shouldn't this list be a part of the "curated list of awesome lists"?

### ISSUE THREAD

**Issue by dmitshur** [AndrewSB/awesome-osx#1]
It's not at https://github.com/sindresorhus/awesome.

Wouldn't it make sense to add it there so it can be more easily found by more people?

**Comment by dmitshur** [comment]
If you do, you should add a badge. https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge

**Comment by AndrewSB** [comment]
I looked into that, but the curated list of awesome only wants lists that are [a couple of weeks old with a good deal of content](https://github.com/sindresorhus/awesome/pull/270). Which definitely makes sense. I'm going to try to re-add it to sindresorhus' list of awesome lists when we it gets more activity and content.

Will definitely add the badge as soon as we're on the list.

**Comment by AndrewSB** [comment]
Speaking of which, thank you for your interest in the repo!
Should have it on the list in no time :smile:
